flags: {}
packages:
- '.'
- location:
    git: https://github.com/mzini/monad-trace
    commit: 488bd2c09e51cbd16581cdd61fe13059ae62e45e
  extra-dep: true
extra-deps:
- smtlib2-1.0
- smtlib2-pipe-1.0
- smtlib2-debug-1.0
- atto-lisp-0.2.2.2
- data-fix-0.0.3
- z3-4.1.0
- typed-process-0.1.0.0
resolver: lts-9.12
flags:
  gubs:
    Z3: false
